.gitignore, README.md, docker-compose.yml, env.example, prisma/schema.prisma
Issue #1   has been resolved in this PR
=> add: docker support

apps/reflect/src/components/auth/AuthContainer.tsx
=> fix: width of `ListItemText` in `AuthContainer`

apps/reflect/src/forms/SecurityForm.tsx
=> update: in the settings page security tab 'show/hide' button 

apps/reflect/src/api/index.ts, apps/reflect/src/components/landing/LandingTexts.tsx, apps/reflect/src/pages/api/cmd/index.ts, apps/reflect/src/pages/api/features.ts, apps/reflect/src/pages/api/twitch/get-bot.ts, package-lock.json
https://user-images.githubusercontent.com/88425310/232823033-4e346c2c-e9ef-4806-906c-9fd89dfb5919.mov
=> update: landingpage

apps/reflect/src/api/index.ts, apps/reflect/src/components/landing/LandingTexts.tsx
=> feat(apps/reflect): add features list to landing page

README.md
Discord repo link fixed in main readme file
=> fix: Discord link fix in main readme

apps/reflect/README.md
=> fix: Reflect readme

apps/reflect/prisma/schema.prisma, apps/reflect/src/components/app/BotActivity.tsx, apps/reflect/src/types/index.ts, apps/twitch-bot/internal/backend/backend.go, apps/twitch-bot/internal/backend/mysql/mysql.go, apps/twitch-bot/internal/handler/privatemessage.go, apps/twitch-bot/internal/models/models.go, apps/twitch-bot/server/server.go
=> feat: add command author info to bot activites

apps/reflect/src/pages/api/features.ts, apps/twitch-bot/internal/command/helpers/helpers.go
update FormatCommandContent function
add {cmd.author} template
=> refactor(apps/twitch-bot): update FormatCommandContent function

apps/reflect/prisma/schema.prisma, apps/twitch-bot/internal/backend/backend.go, apps/twitch-bot/internal/backend/mysql/mysql.go, apps/twitch-bot/internal/command/addcommand.go, apps/twitch-bot/internal/command/addcommandalias.go, apps/twitch-bot/internal/command/command.go, apps/twitch-bot/internal/command/deletecommand.go, apps/twitch-bot/internal/command/deletecommandalias.go, apps/twitch-bot/internal/command/helpers/helpers.go, apps/twitch-bot/internal/command/updatecommand.go, apps/twitch-bot/internal/handler/privatemessage.go, apps/twitch-bot/internal/models/models.go, apps/twitch-bot/server/server.go
Add command alias create & delete and add CheckCommandExists function
=> feat(apps/twitch-bot) add command alias create & delete

apps/twitch-bot/internal/command/helpers/helpers.go
add old string templates for backward compatibility
=> update(apps/twitch-bot): add old string templates

apps/reflect/src/forms/TwitchBotForm.tsx
This PR updates the `onSuccess()` function to replace the `Alert` component with `snackbar`, with the goal of improving the user experience.
- Replaced `Alert` component with `snackbar` in `onSuccess()` function
=> feature(apps/reflect): onSuccess() function to use snackbar instead of Alert for improved user experience

apps/reflect/src/components/app/AppBar/buttons/CommandListButton.tsx, apps/reflect/src/components/app/AppBar/index.tsx, apps/reflect/src/components/app/BotActivity.tsx, apps/reflect/src/components/app/CommandList.tsx, apps/reflect/src/components/landing/LandingTexts.tsx, apps/reflect/src/pages/app/command-list.tsx, apps/reflect/src/server/router/command.ts, apps/reflect/src/server/router/index.ts, apps/reflect/src/types/index.ts
Command deletion is not working properly. The list item of the deleted command is not removed, presumably due to the problem of not being re-rendered.
Command activation/deactivation functionality is not included yet.
=> feat(apps/reflect): create command list

apps/reflect/src/components/landing/LandingGrid.tsx
=> fix/((apps/reflect)): horizontal scrool

apps/reflect/src/components/landing/LandingTexts.tsx
=> update(apps/reflect):in landing page landing Text width

apps/reflect/src/components/app/AppBar/buttons/CommandListButton.tsx, apps/reflect/src/components/app/AppBar/buttons/DrawerButton.tsx, apps/reflect/src/components/app/AppBar/index.tsx, apps/reflect/src/components/app/AppDrawer.tsx
- Removed certain buttons from the `AppBar`.
- Added the `AppDrawer` to create a foundation for future features.
The purpose of this PR is to enhance the user experience by simplifying the `AppBar` and providing a framework for upcoming additions.
https://user-images.githubusercontent.com/88425310/236674252-0490e897-3d59-4764-91ac-0e0d4d10cb27.mov
=> feat(apps/reflect): AppDrawer

apps/reflect/src/components/app/AppDrawer.tsx
https://user-images.githubusercontent.com/88425310/236679163-de7f7757-6c55-4d6d-bf12-c3a7f023a885.mov
=> fix(apps/reflect): if user clicked all command list menu item and path equal all command list page is reload

apps/twitch-bot/internal/backend/backend.go, apps/twitch-bot/internal/backend/postgresql/postgresql.go, apps/twitch-bot/internal/command/addcommand.go, apps/twitch-bot/server/server.go
=> fix(apps/twitch-bot): add command alias check when creating a command

apps/reflect/src/components/app/AppDrawer.tsx
connect issue  #136 
https://github.com/senchabot-dev/monorepo/assets/88425310/1d1d9125-2b92-4eda-9dd0-c4a757e48b67
=> feat(apps/reflect): AppDraw get bots section

apps/reflect/src/components/app/AppBar/buttons/DrawerButton.tsx, apps/reflect/src/components/app/AppDrawer.tsx
Refactored `AppDrawe Button` tooltip and `AppDrawer` command list icon
=> refactor(apps/reflect): AppDrawer & AppDrawerButton

apps/twitch-bot/internal/backend/postgresql/postgresql.go
add deletion of related alias commands when the command is deleted
=> fix(apps/twitch-bot): add deletion of related alias commands

apps/twitch-bot/internal/backend/postgresql/postgresql.go, apps/twitch-bot/internal/command/addcommandalias.go, apps/twitch-bot/server/server.go
Add the creation of an alias command to the command using the alias command
Closes: #103
=> feat(apps/twitch-bot): add the creation of an alias command using the alias command

apps/twitch-bot/internal/backend/backend.go, apps/twitch-bot/internal/backend/postgresql/postgresql.go, apps/twitch-bot/internal/command/deletecommand.go, apps/twitch-bot/internal/command/updatecommand.go, apps/twitch-bot/server/server.go
=> feat(apps/twitch-bot): add update and delete command using the alias command

apps/twitch-bot/internal/command/addcommandalias.go, apps/twitch-bot/internal/command/helpers/helpers.go
Add MakeUniqueArray function to handle duplicates when creating alias commands
=> fix(apps/twitch-bot): add MakeUniqueArray function to handle alias duplicates

apps/twitch-bot/internal/backend/backend.go, apps/twitch-bot/internal/backend/postgresql/postgresql.go, apps/twitch-bot/internal/command/addcommand.go, apps/twitch-bot/internal/command/addcommandalias.go, apps/twitch-bot/internal/command/deletecommand.go, apps/twitch-bot/internal/command/deletecommandalias.go, apps/twitch-bot/internal/command/helpers/helpers.go, apps/twitch-bot/internal/command/updatecommand.go, apps/twitch-bot/server/server.go
Create validate functions
Rename variable and function names
Add command exist check to update and delete commands
=> refactor(apps/twitch-bot): crud commands

apps/reflect/src/forms/TwitchBotForm.tsx
114th and 125th line changed to "Twitch Bot Activity Logs" from "Twitch Bot Activities"
=> Edit Activity Form Label

apps/discord-bot/utils/scheduledEventFunctions.ts
add check for scheduled event creator in checkScheduledEvents function
We need to check if the live stream notification sent by a user or a bot. And we need to check if the scheduled event created by a bot, then bot can delete the scheduled event when the stream is offline.
So, I added a if condition to check if the notification message author is a bot and the event will be deleted is created by a bot.
=> feat(apps/discord-bot): add check for scheduled event creator

apps/reflect/src/forms/TwitchBotForm.tsx
=> fix(apps/reflect): Settings page Text truncation

apps/reflect/src/components/app/CommandList.tsx
https://github.com/senchabot-dev/monorepo/assets/88425310/e70415ce-3dbf-48ec-ad0e-e1d67b704b95
=> feat(apps/reflect): command list search

apps/twitch-bot/internal/command/cmds.go, apps/twitch-bot/internal/command/kampus.go
"!kampus" and "!cmds" command contents updated
=> fix: kampus and cmds command contents

apps/discord-bot/documentation/README.md, apps/discord-bot/documentation/TR/README.md, apps/twitch-bot/documentation/README.md, apps/twitch-bot/documentation/TR/README.md
[docs(apps/twitch-bot): Add Twitch command documentations (EN and TR)](https://github.com/senchabot-dev/monorepo/issues/192)
[docs(apps/discord-bot): Add Discord command documentations (EN and TR)](https://github.com/senchabot-dev/monorepo/issues/193)
=> docs(apps/twitch-bot, apps/discord-bot): Senchabot Usage Manual / Command Documentations (EN and TR)

apps/discord-bot/events/guildCreate.ts, apps/discord-bot/events/guildDelete.ts, apps/discord-bot/events/ready.ts, apps/discord-bot/package.json, apps/discord-bot/utils/dbFunctions.ts, pnpm-lock.yaml
add discord server creation/deletion on ready, guildCreate and guildDelete events
=> feat(apps/discord-bot): add create/delete discord server in database

packages/senchabot-prisma/index.ts, packages/senchabot-prisma/package.json
update prisma exporting
update package.json file according to
=> refactor(packages/senchabot-prisma): update package.json and index.ts

apps/twitch-bot/internal/service/database/mysql/mysql.go, apps/twitch-bot/internal/service/service.go
=> refactor(apps/twitch-bot): rename the PostgreSQL package to MySQL

apps/discord-bot/cmd/main/main.go
map the message content string to lower case
add check if message is older than 14 days
=> fix(apps/discord-bot): add proper response texts and fix a condition in the purge message option

apps/discord-bot/cmd/main/main.go, apps/discord-bot/internal/db/db.go, apps/discord-bot/internal/helpers/helpers.go, apps/discord-bot/internal/service/event/event.go, apps/discord-bot/internal/service/streamer/streamer.go
move related functions to streamer package
=> fix(apps/discord-bot): update streamer announcement system functionality

apps/discord-bot/cmd/main/main.go, apps/discord-bot/internal/helpers/helpers.go, apps/twitch-bot/internal/command/sozluk.go, packages/common/commands/sozluk.go, packages/common/helpers/helpers.go
add common commands package and move sozluk command functions to it
=> refactor: add common commands package and move sozluk command

apps/discord-bot/internal/command/command.go
=> fix(apps/discord-bot): add announcement channel type for channel listing

.github/workflows/discord-bot-deploy.yml
Reverts senchabot-opensource/monorepo#326
We should remove tags.
=> Revert "feat(github-workflows): update discord bot deploy workflow"

apps/discord-bot/cmd/main/main.go, apps/discord-bot/internal/command/addcmdaliascommand.go, apps/discord-bot/internal/command/command.go, apps/discord-bot/internal/command/deletecmdaliascommand.go, apps/discord-bot/internal/db/db.go, apps/twitch-bot/internal/command/addcommandalias.go, apps/twitch-bot/internal/command/deletecommand.go, apps/twitch-bot/internal/command/deletecommandalias.go, apps/twitch-bot/internal/command/helpers/helpers.go, apps/twitch-bot/internal/command/helpers/helpers_test.go, packages/gosenchabot/helpers.go, packages/gosenchabot/helpers_test.go
add command alias feature to Discord bot & refactor Twitch bot with using same functions
=> refactor & add command alias feature to Discord bot

apps/discord-bot/cmd/main/main.go, apps/discord-bot/internal/command/command.go, apps/discord-bot/internal/command/deletecommand.go, apps/discord-bot/internal/command/setcommand.go, apps/discord-bot/internal/helpers/helpers.go, apps/discord-bot/internal/service/event/event.go, apps/discord-bot/internal/service/streamer/streamer.go, packages/gosenchabot/models/models.go, packages/gosenchabot/service/twitch/twitch.go
This pr includes the moving of twitch functions to the gosenchabot package and the refactoring of these functions
=> refactor(apps/discord-bot): move twitch functions under the gosenchabot package

apps/twitch-bot/internal/command/so.go
use strings.TrimPrefix for @ character
=> fix(apps/twitch-bot): update so command

apps/web/src/components/app/AppCookie.tsx, apps/web/src/pages/api/bot/activity.ts, packages/senchabot-prisma/prisma/seed.ts
=> fix(apps/web):frontend integration updates in prisma.shema

apps/twitch-bot/internal/handler/botjoin.go, apps/twitch-bot/internal/service/webhook/botjoin.go
update BotJoin functions to fetch channel names from channel ids
This pr temporarily fixes the issue #372. Another solution will be added with the next pr.
=> refactor(apps/twitch-bot): update BotJoin functions to fetch channel names

packages/senchabot-prisma/prisma/seed.ts
=> feat: discord test data added on prisma seed

apps/discord-bot/internal/handler/guildcreate.go, db/postgresql/discord.go
https://github.com/senchabot-opensource/monorepo/pull/523#issuecomment-2558516039
=> feat(discord-bot): add separate logs to AddServerToDB
